name: CI

on: [push, pull_request]

jobs:
  appcenter_ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: danrabbit/actions/appcenter@master

  lint:

    runs-on: ubuntu-latest
    
    container:
      image: valalang/lint
      
    steps:
    - uses: actions/checkout@v1
    - name: Lint
      run: io.elementary.vala-lint -d .
